# Generated by Django 5.1.2 on 2024-11-01 22:11
from django.db import migrations
class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_wrapped'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='wrapped',
            name='type',
        ),
    ]
