# Generated by Django 5.1 on 2024-11-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrapped",
            name="desc",
            field=models.TextField(default=""),
        ),
    ]
