# Generated by Django 5.1.1 on 2024-11-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_duowrapped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duowrapped',
            name='compatibility_desc',
        ),
    ]
